-- drop table sex_diff;
create table sex_diff(
phenocode                 VARCHAR(255) NOT NULL,
chromosome                TINYINT NOT NULL,
position                  INT NOT NULL,
identitier                varchar(2000) NOT NULL,
reference                 varchar(1000) NOT NULL,
alternate                 varchar(1000) NOT NULL,
A1FREQ                    FLOAT NOT NULL,
A1FREQ_CASES              FLOAT NOT NULL,
A1FREQ_CONTROLS           FLOAT NOT NULL,
INFO                      FLOAT NOT NULL,
N                         INT   NOT NULL,
TEST                      VARCHAR(255) NOT NULL,
BETA                      FLOAT NOT NULL,
SE                        FLOAT NOT NULL,
CHISQ                     FLOAT NOT NULL,
LOG10P                    FLOAT NOT NULL,
males_ID                  VARCHAR(2000) NOT NULL,
males_A1FREQ_CASES        FLOAT NOT NULL,
males_A1FREQ_CONTROLS     FLOAT NOT NULL,
males_N                   INT   NOT NULL,
males_BETA                FLOAT NOT NULL,
males_SE                  FLOAT NOT NULL,
males_LOG10P              FLOAT NOT NULL,
females_ID                VARCHAR(2000) NOT NULL,
females_A1FREQ_CASES      FLOAT NOT NULL,
females_A1FREQ_CONTROLS   FLOAT NOT NULL,
females_N                 INT   NOT NULL,
females_BETA              FLOAT NOT NULL,
females_SE                FLOAT NOT NULL,
females_LOG10P            FLOAT NOT NULL,
diff_beta                 FLOAT NOT NULL,
p_diff                    FLOAT NOT NULL,
CHECK (chromosome >= 1 and chromosome < 27),
CHECK (A1FREQ >= 0 and A1FREQ <= 1),
CHECK (A1FREQ_CASES >= 0 and A1FREQ_CASES <= 1),
CHECK (A1FREQ_CONTROLS >= 0 and A1FREQ_CONTROLS <= 1),
CHECK (INFO >= 0 and INFO <= 1),
CHECK (N >= 0),
CHECK (SE >= 0),
CHECK (CHISQ >= 0),
CHECK (LOG10P >= 0),
CHECK (males_A1FREQ_CASES >= 0),
CHECK (males_A1FREQ_CONTROLS >= 0),
CHECK (males_N >= 0),
CHECK (males_SE >= 0),
CHECK (males_LOG10P >= 0),
CHECK (females_A1FREQ_CASES >= 0),
CHECK (females_A1FREQ_CONTROLS >= 0),
CHECK (females_N >= 0),
CHECK (females_SE >= 0),
CHECK (females_LOG10P >= 0),
CHECK (p_diff >= 0)
);

CREATE INDEX sex_diff_phenocode ON sex_diff (phenocode);
CREATE INDEX sex_diff_cpra      ON sex_diff (chromosome,position,reference(511),alternate(511));
