#!/usr/bin/env python2

# -*- mode: python -*-

# TODO:
# 1. Create a folder `subcommands/`.
# 2. Populate a few subcommands.  What should each have?  Just a function?  A class?
# 3. When someone runs `./pheweb <subcommand>`, check for `subcommands/<subcommand>.py`.  Invoke it with args[1:], config, pheweb_dir, and data_dir.
# 4. Put all of `data/*.{sh,py}` in there, including `phenolist.py` and `run_all.py`.
#    - how should `run_all.py` invoke `./pheweb get_cpras`?  Maybe pass it a reference to the subommand-calling function?
# 5. Fetch config from [$PHEWEB_DIR/config.py, $PWD/config.py, $pheweb_dir/config.py].
# 6. Put data in $data_dir/generated-by-pheweb/
# 7. Set up tests.  Use .gitignore.
# 8. `./server.py --port 5005` -> `./pheweb serve --port 5005`.

'''
make everything subcommands of a common entry-point.
- `./pheweb phenolist glob ...`

move all pheweb-generated data into `$dir/generated-by-pheweb/`.

make a subcommand `./pheweb quickstart '/tmp/phe([0-9]+).tsv.gz'`
- uses `~/my-phewebs/$RANDOM/`
- prepares a pheweb and hosts it on `0.0.0.0:5000`
    - could it open a web browser?  how to do that on linux?

to make templates configurable:
- option 1: (nope)
    - make own templates that extend defaults
    - tell flask to use them
- option 2: (yep)
    - put `custom_templates/` FIRST
    - `region.html` just inherits from `base_region.html` without any changes
    - `custom_templates/region.html` will be override default.
- option 3: (yep)
    - use lots of importing in templates (like exac)
    - `custom_templates/qq.html` overrides the qq plot. (&c)
    - can we namespace templates? (eg, `custom_templates/region/{base,default,tooltip}.html`)

then what about beta/sebeta in tables?  how to make that automatically be used or not?
- no premature optimization, just make it work
- option 1: (plzno)
    - include beta/sebeta in header and row-template and make js hide it if unused
- option 2: (nope)
    - user is responsible for overriding templates to include it.
- option 3: (yep)
    - make a header-template that takes a {variant: true, beta_sebeta: true, ...}
    - likewise for row-template
    - put these two into a {%block%} for {%extends%}ing them
    - to make a clearer code structure, what if you built those two templates together (eg, `if(beta_sebeta){header_template+=...;row_template+=...}`)

then how to get down to only one pheweb install?
- wsgi.wsgi must be in $dir
- `$data_dir/custom_templates/`

Differences between mgi and sardinia-r2
- config.config (minimum_maf, data_dir)
- 0_0
    - not really my problem, but get it out of pheweb/data/
- phewas_significance_threshold (add to config.config)
- about.html text
- index.html <h2>
- inclusion of <th>beta (se)</th> on top_hits and others
    - gonna be solved by above approach
- placeholder="..." on variant.html (ie, pheno names)
    - should this automatically be some real phenotypes?
        - just '&quot;{{ phenolist[0].phenostring || phenolist[0].phenocode }&quot;, &quot;{{ ... }}&quot;, etc.'

so then everything will work but we'll want to work from $dir and use the fullpath for `pheweb.py`.
- at that point it should be easy to switch to `setup.py` and packaging.  but not before then.
- once this works, the directions will be:

   ```
   pip3 install pheweb
   mkdir /var/my-new-pheweb; cd /var/my-new-pheweb
   pheweb quickstart --glob <glob>... # just uses $(basename) as phecode
   pheweb server --port 5003
   ```

make a special `./pheweb augment-like-vb-icd9-phewas`.
- it should be easy to add custom subcommands.
- What if we just had one file for each subcommand (`pheweb/subcommands/<subcommand>.py`), so it was super easy to add more?

use wget (from pypi) instead of /usr/{,local/}bin/wget (https://pypi.python.org/pypi/wget)
'''