# Hacked to handle the change
# in cloud proxy credentials
# 
# See : https://github.com/mrhavens/Dedockify
# docker pull eu.gcr.io/phewas-development/pheweb:prod_4fd92fd_doc_link4 
# docker pull mrhavens/dedockify
# docker run -v /var/run/docker.sock:/var/run/docker.sock --rm mrhavens/dedockify 3de62bf29a59
#
FROM eu.gcr.io/phewas-development/pheweb:prod_4fd92fd_doc_link4
ADD file:8f7dc710e276f54a3a73d34b6b8fa261950a781d68ceb7401fa18dabc601c5a5 in /
ENV CLOUD_SQL_PROXY_CREDENTIAL_FILE /etc/gcp/cloud-sql-credentials.json
ENV CLOUD_SQL_PROXY_INSTANCES /etc/gcp/cloud-sql-credentials.json
ENV PHEWEB_DIR /mnt/nfs/pheweb/r4
ENV LC_CTYPE en_US.UTF-8                                                                                                                                                                                           
ENV LC_ALL en_US.UTF-8                                                                                                                                                                                             
ENV LANG en_US.UTF-8

CMD ["bash"]
ENV PHEWEB_DIR=/mnt/nfs/pheweb/r4
ENV LC_CTYPE=en_US.UTF-8
ENV LC_ALL=en_US.UTF-8
ENV LANG=en_US.UTF-8
RUN /bin/sh -c apt-get update \
    && apt-get install --no-install-recommends texlive wget --yes \
    &&     wget --no-check-certificate https://dl.google.com/cloudsql/cloud_sql_proxy.linux.amd64 -O /usr/local/bin/cloud_sql_proxy \
    &&     chmod +x /usr/local/bin/cloud_sql_proxy
ADD dir:db90ee29a3a36e67d749969f99509da6af26d83beaa73ebbd8140bcbf6b868d3 in /pheweb
RUN /bin/sh -c apt-get update \
    && apt-get install python3-pip libffi-dev libz-dev libssl-dev libbz2-dev liblzma-dev --yes --fix-missing \
    &&     pip3 install cython \
    &&     pip3 install /pheweb
EXPOSE 8080
CMD ["/bin/sh" "-c" "cloud_sql_proxy -instances=$CLOUD_SQL_PROXY_INSTANCES -credential_file=$CLOUD_SQL_PROXY_CREDENTIAL_FILE & cd $PHEWEB_DIR \
    && pheweb serve --port 8080 --num-workers 4"]
COPY file:f9f1dd706e4f7273ff51a27a0ac62950eb04a45768c89352f5157cd58549226f in /usr/local/lib/python3.5/dist-packages/pheweb/serve/
COPY file:c9be2be5c3a7d489adb6893db7855556989c94807082a0fad2c71e18590f6150 in /usr/local/lib/python3.5/dist-packages/pheweb/serve/templates/

